### ISSUE TITLE
Updating boolean value to False does not work

### ISSUE THREAD

**Issue by iotasquared** [octabytes/FireO#34]
class User(Model):
  online = BooleanField()

u = User()
u.save()
user_key = u.key

u = User()
u.online = False
u.update(user_key)

Gives the following error:
Traceback (most recent call last):
  File "/Users/dafzal/code/insurita/backend_prototype/firebase_test.py", line 35, in <module>
    u.update(user_key)
  File "/Users/dafzal/code/insurita/venv/lib/python3.7/site-packages/fireo/models/model.py", line 419, in update
    return self.__class__.collection._update(self, transaction=transaction, batch=batch, **updated_fields)
  File "/Users/dafzal/code/insurita/venv/lib/python3.7/site-packages/fireo/managers/managers.py", line 206, in _update
    return self.queryset.update(mutable_instance, transaction, batch, **kwargs)
  File "/Users/dafzal/code/insurita/venv/lib/python3.7/site-packages/fireo/queries/query_set.py", line 80, in update
    return UpdateQuery(self.model_cls, mutable_instance, **kwargs).exec(transaction_or_batch)
  File "/Users/dafzal/code/insurita/venv/lib/python3.7/site-packages/fireo/queries/update_query.py", line 90, in exec
    return query_wrapper.ModelWrapper.from_query_result(self.model, self._raw_exec())
  File "/Users/dafzal/code/insurita/venv/lib/python3.7/site-packages/fireo/queries/update_query.py", line 83, in _raw_exec
    ref.update(self._parse_field())
  File "/Users/dafzal/code/insurita/venv/lib/python3.7/site-packages/google/cloud/firestore_v1/document.py", line 381, in update
    batch.update(self, field_updates, option=option)
  File "/Users/dafzal/code/insurita/venv/lib/python3.7/site-packages/google/cloud/firestore_v1/batch.py", line 112, in update
    reference._document_path, field_updates, option
  File "/Users/dafzal/code/insurita/venv/lib/python3.7/site-packages/google/cloud/firestore_v1/_helpers.py", line 862, in pbs_for_update
    raise ValueError("Cannot update with an empty document.")
ValueError: Cannot update with an empty document.

I think the problem is in _parse_field
if v:
        field_dict[f.db_column_name] = v

^ means you cant update a model for any v where bool(v) = False

**Comment by AxeemHaider** [comment]
Your issue if fixed.  

And one other thing you don't need to create new object and remembering the key to update the document.

Use this it will work same
```python
u = User()
u.save()

u.online = False
u.update(user_key)
```

Read More about pros and cons of using `key` when updating documents [Updating Data](https://octabyte.io/FireO/querying-data/updating-data/)

**Comment by iotasquared** [comment]
FYI, I don't think this solution works. Setting a value to 0 or None will throw an error.

**Comment by iotasquared** [comment]
@AxeemHaider

**Comment by AxeemHaider** [comment]
Sorry, what you are saying everything is working fine for me. Send me the error logs.
Or any example how I can regenerate this error. 

If you are trying to set zero(0) in `BooleanField` then it will throw error because you can't set `int` to `bool` field
