### ISSUE TITLE
QueryIterator throws exception when result includes empty document

### ISSUE THREAD

**Issue by ka2ush19e** [octabytes/FireO#87]
When query result includes empty document, query iteration fails.

To reproduce:
```python
from fireo.fields import TextField
from fireo.models import Model

class Company(Model):
    name = TextField()

Company.collection.create(name="Abc_company")
Company.collection.create()
Company.collection.create()

assert len(list(Company.collection.fetch())) == 3
```

The following exception is thrown:
```
Traceback (most recent call last):
  File "app.py", line 12, in <module>
    assert len(list(Company.collection.fetch())) == 3
  File "/usr/local/lib/python3.8/site-packages/fireo//queries/query_iterator.py", line 41, in __next__
    m._update_doc = self.query._update_doc_key(m)
  File "/usr/local/lib/python3.8/site-packages/fireo//queries/filter_query.py", line 437, in _update_doc_key
    update_doc_key = model.key
AttributeError: 'NoneType' object has no attribute 'key'
```

**Comment by AxeemHaider** [comment]
Empty document can not be saved now. 

Update to `version 1.3.9`
